### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mistahanish** [codecrafters-io/build-your-own-x#1013]
The link to the [Ruby: Build your own fast, persistent KV store in Ruby](https://dinesh.wiki/posts/build-your-own-persistent-kv-store/) doesn't work. Might have to change it to this [Ruby: Build your own fast, persistent KV store in Ruby](https://dineshgowda.com/posts/build-your-own-persistent-kv-store/).

**Comment by rohitpaulk** [comment]
Open to PRs!

**Comment by karandeeppotato** [comment]
I'll do it..can you assign me :)

**Comment by karandeeppotato** [comment]
Submitted a PR !

**Comment by rohitpaulk** [comment]
https://github.com/codecrafters-io/build-your-own-x/pull/1014
