### ISSUE TITLE
Visual Recognition System : Not available/broken Link

### ISSUE THREAD

**Issue by bugslayer01** [codecrafters-io/build-your-own-x#1039]
Under the section Visual Recognition System 
developing a license plate recognition system with machine learning in python  is not not being supported any more
i think it should be removed 

![image](https://github.com/codecrafters-io/build-your-own-x/assets/65941949/9c34423d-64d0-4215-a948-43422d123868)

**Comment by FabriLluvia** [comment]
Well, for me, works. I hope [this file](https://github.com/user-attachments/files/17385527/Developing.a.License.Plate.Recognition.System.with.Machine.Learning.in.Python._.by.Femi.Oladeji._.Devcenter.Square.Blog._.Medium.zip) helps, but it doesn't contain code. For the URL, visit https://medium.com/devcenter/developing-a-license-plate-recognition-system-with-machine-learning-in-python-787833569ccd . If you have a VPN, connect to Colombia, for me, it worked.

**Comment by bugslayer01** [comment]
@FabriLluvia Thanks  for ur help, now it's working for me as well
