### ISSUE TITLE
Won't this be confused with X (formerly known as Twitter)?

### ISSUE THREAD

**Issue by adalfarus** [codecrafters-io/build-your-own-x#1085]
Maybe you could think about changing the name to somthing different and linking the current page to that?

**Comment by adalfarus** [comment]
(When I first heard about it I thought exactly that and nearly didn't check it out as I'm not into webdev)

**Comment by rohitpaulk** [comment]
Prior to the Twitter name change, people confused this with https://en.wikipedia.org/wiki/X_Window_System 😛 No intentions to change the name as of now :)

Thanks for raising this though!
