### ISSUE TITLE
Link unreachable

### ISSUE THREAD

**Issue by GodlySchnoz** [codecrafters-io/build-your-own-x#1242]
Hi i believe the link for the [Java: How to create your own simple 3D render engine in pure Java](http://blog.rogach.org/2015/08/how-to-create-your-own-simple-3d-render.html) is down, i checked and the domain name is registered until 2027 so no problems on that end but even checking from multiple countries it still didn't connect (nominally i tried from Italy, Switzerland and the Netherlands )

**Comment by FabriLluvia** [comment]
Well, I tried in Colombia, and it is not down. I hope this helps.
[How to create your own simple 3D render engine in pure Java.zip](https://github.com/user-attachments/files/17385437/How.to.create.your.own.simple.3D.render.engine.in.pure.Java.zip)

**Comment by GodlySchnoz** [comment]
Guess that since the server is in Russia it might block off European IPs and maybe USA/Canadian ones too

**Comment by FabriLluvia** [comment]
Well, I guess.
I will try it. 3:20 UTC-5.

VPN: Urban VPN.
3:21 UTC-5, In USA, it works.
3:22 UTC-5, In UK, it works.
3:23 UTC-5, In Germany, it works.
3:23 UTC-5, In Russia, it works.
3:24 UTC-5, In Ukraine, it works.

**Comment by GodlySchnoz** [comment]
yea now i can reach it too from Italy and switzerland, guess the server was down for maintenance or they fixed the issue between my first comment and your answer (actually didn't check after the answer as i was not home and forgot once i returned)
