### ISSUE TITLE
THANKS 

### ISSUE THREAD

**Issue by tlynetteb** [codecrafters-io/build-your-own-x#315]
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by parro-it** [comment]
I join the thanks, this collection of tutorials is very inspiring!

**Comment by caiodomingues** [comment]
I join the thanks, this collection of tutorials is very inspiring! ²

**Comment by Matrix89** [comment]
I join the thanks, this collection of tutorials is very inspiring!

**Comment by tlynetteb** [comment]
i am lost

**Comment by danistefanovic** [comment]
Thanks a lot, guys! I really appreciate it. If you're interested in supporting this project, you can help me review open submissions by leaving comments and "reactions" (e.g., thumbs up/down). 🙌

**Comment by azcvcza** [comment]
good job

**Comment by amirouche** [comment]
> you can help me review open submissions

Done that :1st_place_medal:

**Comment by ranggakd** [comment]
well I think we could close this issue to clear up the issue more now
