### ISSUE TITLE
WebGL + Rust: Basic Water Tutorial

### ISSUE THREAD

**Issue by Julien-Broyard** [codecrafters-io/build-your-own-x#317]
### Main programming language
Rust

### Tutorial title
WebGL + Rust: Basic Water Tutorial

### Tutorial URL
www.chinedufn.com/3d-webgl-basic-water-tutorial/

### Category
* [x] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by rohitpaulk** [comment]
Added in https://github.com/codecrafters-io/build-your-own-x/commit/534ee2cd6567e9d24424cbfd20cdb0354d0bdc91!
