### ISSUE TITLE
Writing a Command Line Tool in Rust

### ISSUE THREAD

**Issue by Julien-Broyard** [codecrafters-io/build-your-own-x#319]
### Main programming language
Rust

### Tutorial title
Writing a Command Line Tool in Rust

### Tutorial URL
https://mattgathu.github.io/writing-cli-app-rust/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [x] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by rugk** [comment]
Maybe/alternatively one should possibly also point to https://rust-lang-nursery.github.io/cli-wg/

**Comment by rohitpaulk** [comment]
Added both! https://github.com/codecrafters-io/build-your-own-x/commit/2d75e52debb63d04332f4b08e129828636ee9216
