### ISSUE TITLE
Learning Rust by Writing a Command Line App in 15 Minutes

### ISSUE THREAD

**Issue by Julien-Broyard** [codecrafters-io/build-your-own-x#320]
### Main programming language
Rust

### Tutorial title
Learning Rust by Writing a Command Line App in 15 Minutes

### Tutorial URL
https://rust-lang-nursery.github.io/cli-wg/index.html

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [x] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by rohitpaulk** [comment]
Added in https://github.com/codecrafters-io/build-your-own-x/commit/2d75e52debb63d04332f4b08e129828636ee9216
