### ISSUE TITLE
Let’s go write a Lisp

### ISSUE THREAD

**Issue by lmintmate** [codecrafters-io/build-your-own-x#344]
### Main programming language

Javascript
### Tutorial title

Let’s go write a Lisp ‐ part one
### Tutorial URL
https://idiocy.org/lets-go-write-a-lisp/part-1.html
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [x] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

P.S. This article has two parts. The second part is linked to at the bottom of the first one.

**Comment by rohitpaulk** [comment]
Added in https://github.com/codecrafters-io/build-your-own-x/commit/15066dd894703a2bb6b48cbfae10b9d54ef4a139, thanks @lmintmate!
