### ISSUE TITLE
Ray Tracing in a Weekend

### ISSUE THREAD

**Issue by paralysedforce** [codecrafters-io/build-your-own-x#550]
### Main programming language

C++

### Tutorial title

Ray Tracing in One Weekend

### Tutorial URL
https://raytracing.github.io/books/RayTracingInOneWeekend.html

### Category
* [x] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by JC-ProgJava** [comment]
@paralysedforce perhaps https://raytracing.github.io/ would be a better link(there are three books, this is just one of them)?
