### ISSUE TITLE
Create Your Own CLI Tool

### ISSUE THREAD

**Issue by yairhaimo** [codecrafters-io/build-your-own-x#568]
### Main programming language

Javascript

### Tutorial title

Create Your Own CLI Tool
### Tutorial URL
https://citw.dev/tutorial/create-your-own-cli-tool

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [x] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by ranggakd** [comment]
The link is cool, mate @yairhaimo 
Please make a [PR](https://github.com/codecrafters-io/build-your-own-x/pulls) immediately and reference this PR by adding `#your_issue_number` which is #568

**Comment by yairhaimo** [comment]
Opened a PR. Thanks!
