### ISSUE TITLE
Audio finder printing with Python

### ISSUE THREAD

**Issue by angpappas** [codecrafters-io/build-your-own-x#573]
### Tutorial URL
https://willdrevo.com/fingerprinting-and-audio-recognition-with-python/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ *] Uncategorized

**Comment by themotu** [comment]
This is not a tutorial

**Comment by PedroCisnerosSantana** [comment]
Not a tutorial, this can be closed

**Comment by ranggakd** [comment]
Please close this issue respectfully @angpappas 
We already know the vote based on the reaction now
Thank you
