### ISSUE TITLE
A new C++ tutorial: Steganography - Hiding Information in Images

### ISSUE THREAD

**Issue by feider** [codecrafters-io/build-your-own-x#608]
### Main programming language
C++

### Tutorial title
Steganography - Hiding Information in Images

### Tutorial URL
https://www.feider.space/art/en/steganotut.html

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by elliotwutingfeng** [comment]
Link is dead :(

**Comment by rohitpaulk** [comment]
Same here, I get a 404.
