### ISSUE TITLE
Face Mask Detector

### ISSUE THREAD

**Issue by ShivamBhosale** [codecrafters-io/build-your-own-x#644]
### Main programming language

Python
### Tutorial title

Face Mask Detector
### Tutorial URL
https://teaandtech.hashnode.dev/face-mask-detector
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [x] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by aryasoni98** [comment]
Could I work on this?

**Comment by ShivamBhosale** [comment]
> Could I work on this?

Yeah, I have updated the link
