### ISSUE TITLE
Lack of Rust support

### ISSUE THREAD

**Issue by blankRiot96** [codecrafters-io/build-your-own-x#654]
I find a lot of Python articles and resources provided for almost everything which is great. But I am also a Rust developer, and find that I could barely find any Rust in here
I think it would be great if you could collect some Rust resources

**Comment by 4tydev** [comment]
I agree. You can also find tutorials and help adding them too!

**Comment by rohitpaulk** [comment]
Happy to accept submissions for Rust!

**Comment by rebuilt** [comment]
https://github.com/osynavets/build-your-own-x-in-rust

**Comment by rohitpaulk** [comment]
@rebuilt nice find!
