### ISSUE TITLE
Text Editor in Rust

### ISSUE THREAD

**Issue by oOperaho** [codecrafters-io/build-your-own-x#728]
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [x] Uncategorized

**Comment by devdave** [comment]
+1 for Hecto.  I really enjoyed that tutorial.  

Also its odd but there is a text editor section https://github.com/codecrafters-io/build-your-own-x#build-your-own-text-editor

**Comment by spikecodes** [comment]
+1 for Hecto

**Comment by guuzaa** [comment]
👍 
I like the tutorial too. By the way, I have pulled a PR https://github.com/codecrafters-io/build-your-own-x/pull/751 .
