### ISSUE TITLE
Browser

### ISSUE THREAD

**Issue by gmmkmtgk** [codecrafters-io/build-your-own-x#741]
Any good link to make entire Browser like google chrome, Firefox, etc

**Comment by TeHMoroS** [comment]
You might want to try: https://browser.engineering/

**Comment by gmmkmtgk** [comment]
Thanks

Due you have knowledge that how can we create exe setup for Windows, setup
for other os like linux and mac

From our codebase which is written in python

And from that setup one can install what we have created. Instead of typing
python file name in cmd

One more thing sometimes we also create app for mobile phone. Due you have
idea how can python code can be converted to ios, apk file.

**Comment by TeHMoroS** [comment]
Take a look here: https://packaging.python.org/en/latest/overview/#bringing-your-own-python-executable

Read about "freezing" your code ("Bringing your own Python executable" section). You can use solutions like pyInstaller to distribute your Python code in a form of an executable file.

**Comment by gmmkmtgk** [comment]
And for mobile apps?

**Comment by TeHMoroS** [comment]
> And for mobile apps?

That's a whole other world that I don't think Python is well suited for. I might be wrong though - I'm neither a mobile dev, nor a Python dev by trade. There seem to be some solutions like Kivy or BeeWare, but I know nothing about them.

**Comment by gmmkmtgk** [comment]
now a days we see same application for mac, linux, windows, Android, IOS

So which tech stack he/she should use
based on the various category of application

And I am also curious about  other software categories apart from
application software like

   - System Software.
   - Firmware.
   - Programming Software.
   - Driver Software.
   - Freeware.
   - Shareware


Like there is Android and iOS app for vs code also. So did they manage to
do so.

**Comment by Ryan1729** [comment]
[VS code is open source](https://github.com/microsoft/vscode) so you can look and see how they did it. 

I think vs code on iOS and Android is just using the web browser to access an instance running on a server somewhere.

But in principle I don’t think it is impossible to have a version really running on mobile devices.
