### ISSUE TITLE
Javascript Neural network link unavailable

### ISSUE THREAD

**Issue by ShahriarKh** [codecrafters-io/build-your-own-x#755]
https://franpapers.com/en/machine-learning-ai-en/2017-neural-network-implementation-in-javascript-by-an-example/

The website is no longer available.

**Comment by MuhammedZakir** [comment]
IMHO, we should check webarchive before removing a link. Some tutorials are too good to miss. :-)

**Comment by ShahriarKh** [comment]
I agree. Replacing the link with web archive version is better than completely removing it.
