### ISSUE TITLE
Looking for a TOTP 2fa app from scratch guide

### ISSUE THREAD

**Issue by Wykeless** [codecrafters-io/build-your-own-x#801]
Not submitting a guide or anything nor do I know if this is the right place to ask this...

So Im trying to create my own TOTP 2fa app from scratch and this repo does not seem to have one. The terms I searched for was: '2fa', 'two-factor' , 'two factor', 'multi factor' ,'multi-factor' and nothing came up.

Was hoping that someone can point me into the right direction and/or add a guide to this repo please

**Comment by jagarsoft** [comment]
What about?
https://en.wikipedia.org/wiki/Time-based_one-time_password
https://jumpcloud.com/blog/totp-2fa-pros-cons

https://www.google.com/search?q=TOTP+2fa&rlz=1C1GCEU_enES1019ES1019&oq=TOTP+2fa&aqs=chrome..69i57j0i22i30l9.1303j0j15&sourceid=chrome&ie=UTF-8

Good luck!!
