### ISSUE TITLE
Dead Link (Error 401 - Unauthorized)

### ISSUE THREAD

**Issue by chwa982** [codecrafters-io/build-your-own-x#823]
Java: 3D Game Development with LWJGL 3 https://lwjglgamedev.gitbooks.io/3d-game-development-with-lwjgl/content/

- Error 401. Unauthorized & inaccessible due to permissions/credentials. Title (on browser's title bar) reads "Page Not Found".

**Comment by Seven-Y-Q-Guo** [comment]
No issues from my side, please can you try once again?

**Comment by rohitpaulk** [comment]
Yeah, seems to work for me to... @chwa982 feel free re-open if you're able replicate 🙂
