### ISSUE TITLE
Add "Build your own CDN"

### ISSUE THREAD

**Issue by guptaanmol184** [codecrafters-io/build-your-own-x#839]
### Main programming language
Lua

### Tutorial title
CDN Up and Running - Building a CDN from Scratch to Learn 

### Tutorial URL
https://github.com/leandromoreira/cdn-up-and-running

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [x] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [x] Web Server
* [ ] Uncategorized

**Comment by rohitpaulk** [comment]
Added in https://github.com/codecrafters-io/build-your-own-x/commit/4219a10894c9e4d75557b365bc77270a8d59eebf - thanks for the submission!
