### ISSUE TITLE
Build a LMS

### ISSUE THREAD

**Issue by akins-dev** [codecrafters-io/build-your-own-x#843]
Can anyone help with building a learning management system?

**Comment by Abdelrhman-Ashraf** [comment]
I can help you with the backend using Java

**Comment by akins-dev** [comment]
Okay

**Comment by Zeddaxe** [comment]
i am also wondering here to learn the same

**Comment by rohitpaulk** [comment]
Hey all! Closing this since there isn't a submission attached + the topic doesn't seem relevant to the style of tutorials we have here, which is "re-creating" technologies from scratch.
