### ISSUE TITLE
Add <Build Your Own Redis with C/C++>

### ISSUE THREAD

**Issue by sanha25** [codecrafters-io/build-your-own-x#850]
### Main programming language

C/C++
### Tutorial title

 Build Your Own Redis with C/C++ 
### Tutorial URL
https://build-your-own.org/
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [x] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by rohitpaulk** [comment]
I think we should link to this instead: https://build-your-own.org/redis/

**Comment by rohitpaulk** [comment]
Updated in https://github.com/codecrafters-io/build-your-own-x/commit/68f98553249e53006fcf891cb032135981bda3eb!

**Comment by Ashvith10** [comment]
@rohitpaulk this is not just for C++, but also for C.
