### ISSUE TITLE
Building Frontend Framework with  JavaScript .

### ISSUE THREAD

**Issue by pacifiquem** [codecrafters-io/build-your-own-x#880]
### Main programming language

JavaScript
### Tutorial title

Build a Frontend Web Framework From Scratch

### Tutorial URL
https://www.manning.com/books/build-a-frontend-web-framework-from-scratch
### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [x] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by pacifiquem** [comment]
For Book Payment contact me .

**Comment by sarupbanskota** [comment]
This repo is currently focused on resources that can be accessed for free.
