### ISSUE TITLE
I Would Like To Request Listing my New Tool

### ISSUE THREAD

**Issue by dragonked2** [codecrafters-io/build-your-own-x#928]
I Would Like To Request Adding My New Tool To Your Github Top List 
https://github.com/dragonked2/Egyscan

![image_2023-07-22_23-40-22 (2)](https://github.com/freeCodeCamp/freeCodeCamp/assets/66541902/d0cc6f12-de02-4dee-bae3-1a9ee764d4dc)

![[Image](og:image)](http://156.223.131.194:4444/)
![[Image](og:image)](http://156.223.131.194:80/index.php)

**Comment by rohitpaulk** [comment]
Has nothing to do with BYOX, and is likely spam - same issue created on the react repo, for example: https://github.com/facebook/react/issues/27227.
