### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by munenecarl** [codecrafters-io/build-your-own-x#939]
Python: Build your own license plate registration system using machine learning link is broken [https://blog.devcenter.co/developing-a-license-plate-recognition-system-with-machine-learning-in-python-787833569ccd]

**Comment by Rai-Sahil** [comment]
Hi @munenecarl ,

Made a PR for this issue, #956

**Comment by Rai-Sahil** [comment]
@munenecarl 

Is it not an issue anymore

**Comment by munenecarl** [comment]
Nah, since you already opened a pull request, I closed it but let me reopen
it then

**Comment by Rai-Sahil** [comment]
Oh ok ok yeah. Sorry my bad it’s my first contribution. I didn’t know how it works. Sorry you can close it if you want. I did fixed it, don’t know when PR will be accepted.

**Comment by munenecarl** [comment]
No, problem, I'll close it when your PR has been merged

**Comment by cakepans** [comment]
I did manage to find the new link I believe.
https://medium.com/devcenter/developing-a-license-plate-recognition-system-with-machine-learning-in-python-787833569ccd

**Comment by munenecarl** [comment]
@cakepans 
I do believe that this is the intended article
