### ISSUE TITLE
Write yourself a Git in Golang

### ISSUE THREAD

**Issue by ignorantshr** [codecrafters-io/build-your-own-x#982]
### Main programming language

Go

### Tutorial title

Write yourself a Git in Golang!

### Tutorial URL
[mgit](https://github.com/ignorantshr/mgit) implements [Write yourself a Git!](https://wyag.thb.lt) in Go.

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [x] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by rohitpaulk** [comment]
Hi, thanks for submitting! Do you have a tutorial/guide that goes along with this?

**Comment by ignorantshr** [comment]
Here's the python guide I find in this repository [Write yourself a Git!](https://wyag.thb.lt/), I just implemented it in Go.

**Comment by ignorantshr** [comment]
> Hi, thanks for submitting! Do you have a tutorial/guide that goes along with this?

Here's the python guide I find in this repository [Write yourself a Git!](https://wyag.thb.lt/), I just implemented it in Go.

**Comment by rohitpaulk** [comment]
Gotcha. We already have Write yourself a Git listed as a tutorial in the repository. If you find other such tutorials, please let us know!
