### ISSUE TITLE
Bug: Functionality to *Table of Contents*

### ISSUE THREAD

**Issue by KreativKrish** [codecrafters-io/build-your-own-x#992]
## Steps to reproduce
1. Visit this URL: https://build-your-own-x.vercel.app/ 
2. Click on the Table of Contents on the left navigation bar.
3. Observe the error: It does not navigate to the expected destination.

### Expected Behavior 

The Table of Contents should be displayed in a concise manner.

### Category
* [ ] Uncategorized

**Comment by saturnaliam** [comment]
I believe this website is made by someone else, not the people who run this repository. Try making the issue [here](https://github.com/kjj6198/build-your-own-x/), that seems to be the repository for the website.

**Comment by rohitpaulk** [comment]
Yep, correct - thanks @saturnaliam!
