### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by DoDesCadeaux** [codecrafters-io/build-your-own-x#994]
### Tutorial title

how to write an emulator chip 8 interpreter
### Tutorial URL
http://www.multigesture.net/articles/how-to-write-an-emulator-chip-8-interpreter/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [X] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by prodskimaya** [comment]
I think I may have found the fixed link here:
https://multigesture.net/articles/how-to-write-an-emulator-chip-8-interpreter/

I'll see if there is a pull request for it, if not I'll make one

**Comment by DoDesCadeaux** [comment]
Thanks a lot!
